# --- Basic options --- #
# See https://github.com/pages-themes/minimal
# for more

# Name of website
title: Base space

# Short description of your site
description: I am a Postdoctoral Fellow at the Institute for Quantum Computing – University of Waterloo.

# Your name to show in the footer
author: Rodolfo R. Soldati
email: rreissol@uwaterloo.ca

# GitHub Pages theme
theme: jekyll-theme-minimal

# Logo
logo: "./assets/img/me.jpg"

markdown: kramdown

kramdown:
  input: kramdown

plugins:
# Separates posts into pages with paginate
# See: https://jekyllrb.com/docs/pagination/
  - jekyll-paginate
# Creates a sitemap.xml
  - jekyll-sitemap

# Number of posts in each page, with paginate:
paginate: 3
